---
galaxy_info:
  author: gano
  description: os initial settings
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 6
  galaxy_tags:
    - centos
    - initial
    - package
    - yum
