---
- name: install / Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ nginx_packages }}"

- name: install / Install required python packages
  pip:
    name: "{{ item }}"
  with_items: "{{ nginx_pip_packages }}"
