---
- include_vars:
    file: "{{ ansible_distribution }}.yml"
    name: git

- name: Git packages install
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ git.required_packages }}"
