---
- name: composer / download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ home_dir }}/composer-setup.php"

- name: composer / install composer
  block:
  - name: composer / composer-setup
    command: "php composer-setup.php"
    args:
      chdir: "{{ home_dir }}"

  - name: composer / remove composer-setup.php
    file:
      state: absent
      path:  "{{ home_dir }}/composer-setup.php"

- name: commposer / move composer.phar
  command: mv "{{ home_dir }}/composer.phar" "{{ php_composer_path }}"
