---
- name: app / git pull
  become_user: "{{ user }}"
  git:
    repo: "{{ app_repository_url }}"
    accept_hostkey: yes
    dest: "{{ app_dir }}"
    refspec: '+refs/heads/*:refs/remotes/origin/*'
    update: yes
  when: app_vendor_dir.stat.exists == false
