---

- name: install / Import repository
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ php_repositories }}"

- name: install / required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ php_packages }}"
