---
- name: ssh / add github ssh key
  copy:
    src: id_rsa
    dest: "/home/vagrant/.ssh/crypto_payment_pf"
    owner: vagrant
    group: vagrant
    mode:  0600

- name: ssh / ssh config
  copy:
    src: config
    dest: "/home/vagrant/.ssh/config"
    owner: vagrant
    group: vagrant
    mode:  0644
