---
maven_version: "{{ maven_version_specified | default('3.3.9') }}"
maven_major_version: "{{ maven_version | regex_search('^[0-9]+')}}"
maven_target_url: "http://www-eu.apache.org/dist/maven/maven-{{ maven_major_version }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
maven_install_dir: "/opt"
